package com.example.diary_kotlin_simbirsoft

import io.realm.RealmObject
import io.realm.annotations.Ignore
import io.realm.annotations.PrimaryKey
import io.realm.annotations.Required


open class Deal : RealmObject() {
    // Standard getters & setters generated by your IDE…
    @PrimaryKey
    @Required // optional, but recommended.
    var id: String? = null

    var name: String? = null
    var color: String? = null
    var time_start: Int = 0
    var time_finish: Int = 24*60
    var date: String? = null
    var description: String? = null

    @Ignore
    var sessionId = 0
}

