package com.example.diary_kotlin_simbirsoft

import io.realm.RealmObject
import io.realm.annotations.Ignore


class Deal /*: RealmObject()*/ {
    // Standard getters & setters generated by your IDE…
    var name: String? = null
    var id: Int? = null
    var color: String? = null
    var time_start: Int = 0
    var time_finish: Int = 24*60
    var date: Int? = null
    var description: String? = null

    @Ignore
    var sessionId = 0
}

